#!/bin/bash
############################
# .make.sh
# This script creates symlinks from the home directory to any desired dotfiles in ~/dotfiles
############################

########## Variables

dir=~/dotfiles                    # dotfiles directory
files="Xmodmap bashrc vimrc i3 xinitrc other bash_profile inputrc"    # list of files/folders to symlink in homedir

##########


# change to the dotfiles directory
echo "Changing to the $dir directory"
cd $dir

# create symlinks 
for file in $files; do
    echo "Creating symlink to $file in home directory."
    ln -fs $dir/$file ~/.$file
done
