#!/bin/bash
############################
# .make.sh
# This script creates symlinks from the home directory to any desired dotfiles in ~/dotfiles
############################

########## Variables

dir=~/dotfiles                    # dotfiles directory
files="gitconfig Xmodmap bashrc bash_aliases i3 xinitrc other vimperatorrc git-prompt.sh i3status.conf vimrc.before bash_profile inputrc curr.png"    # list of files/folders to symlink in homedir

##########


# change to the dotfiles directory
echo "Changing to the $dir directory"
cd $dir

# create symlinks 
for file in $files; do
    echo "Creating symlink to $file in home directory."
    ln -fs $dir/$file ~/.$file
done
